"""Create legal_ontology table

Revision ID: 23a7069e666a
Revises: 
Create Date: 2025-09-30 15:21:03.367033

"""
from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic
revision = '23a7069e666a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_ontology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_legal_ontology_id'), 'legal_ontology', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_ontology_id'), table_name='legal_ontology')
    op.drop_table('legal_ontology')
    # ### end Alembic commands ###
